image: Ubuntu1804

version: 1.6.6.{build}

branches:
    only:
        - master

environment:
    matrix:
        - GOOS: windows
          GOARCH: amd64
          PREFIX: windows-amd64
          SUFFIX: .exe
        - GOOS: darwin
          GOARCH: amd64
          PREFIX: darwin-amd64
          SUFFIX: 
        - GOOS: linux
          GOARCH: amd64
          PREFIX: linux-amd64
          SUFFIX: 
        - GOOS: freebsd
          GOARCH: amd64
          PREFIX: freebsd-amd64
          SUFFIX: 
        - GOOS: netbsd
          GOARCH: amd64
          PREFIX: netbsd-amd64
          SUFFIX: 
        - GOOS: openbsd
          GOARCH: amd64
          PREFIX: openbsd-amd64
          SUFFIX: 
        - GOOS: dragonfly
          GOARCH: amd64
          PREFIX: dragonfly-amd64
          SUFFIX: 
        - GOOS: solaris
          GOARCH: amd64
          PREFIX: solaris-amd64
          SUFFIX: 
        - GOOS: windows
          GOARCH: 386
          PREFIX: windows-386
          SUFFIX: .exe
        - GOOS: linux
          GOARCH: 386
          PREFIX: linux-386
          SUFFIX: 
        - GOOS: freebsd
          GOARCH: 386
          PREFIX: freebsd-386
          SUFFIX: 
        - GOOS: netbsd
          GOARCH: 386
          PREFIX: netbsd-386
          SUFFIX: 
        - GOOS: openbsd
          GOARCH: 386
          PREFIX: openbsd-386
          SUFFIX: 
        - GOOS: linux
          GOARCH: arm
          GOARM: 5
          PREFIX: linux-armv5
          SUFFIX: 
        - GOOS: linux
          GOARCH: arm
          GOARM: 6
          PREFIX: linux-armv6
          SUFFIX: 
        - GOOS: linux
          GOARCH: arm
          GOARM: 7
          PREFIX: linux-armv7
          SUFFIX: 
        - GOOS: freebsd
          GOARCH: arm
          PREFIX: freebsd-arm
          SUFFIX: 
        - GOOS: netbsd
          GOARCH: arm
          PREFIX: netbsd-arm
          SUFFIX: 
        - GOOS: linux
          GOARCH: arm64
          PREFIX: linux-arm64
          SUFFIX: 
        - GOOS: linux
          GOARCH: ppc64
          PREFIX: linux-ppc64
          SUFFIX: 
        - GOOS: linux
          GOARCH: ppc64le
          PREFIX: linux-ppc64le
          SUFFIX: 
        - GOOS: linux
          GOARCH: mips64
          GOMIPS: hardfloat
          PREFIX: linux-mips64-hardfloat
          SUFFIX: 
        - GOOS: linux
          GOARCH: mips64
          GOMIPS: softfloat
          PREFIX: linux-mips64-softfloat
          SUFFIX: 
        - GOOS: linux
          GOARCH: mips64le
          GOMIPS: hardfloat
          PREFIX: linux-mips64le-hardfloat
          SUFFIX: 
        - GOOS: linux
          GOARCH: mips64le
          GOMIPS: softfloat
          PREFIX: linux-mips64le-softfloat
          SUFFIX: 
        - GOOS: linux
          GOARCH: mips
          GOMIPS: hardfloat
          PREFIX: linux-mips-hardfloat
          SUFFIX: 
        - GOOS: linux
          GOARCH: mips
          GOMIPS: softfloat
          PREFIX: linux-mips-softfloat
          SUFFIX: 
        - GOOS: linux
          GOARCH: mipsle
          GOMIPS: hardfloat
          PREFIX: linux-mipsle-hardfloat
          SUFFIX: 
        - GOOS: linux
          GOARCH: mipsle
          GOMIPS: softfloat
          PREFIX: linux-mipsle-softfloat
          SUFFIX: 
        - GOOS: linux
          GOARCH: s390x
          PREFIX: linux-s390x
          SUFFIX: 

clone_depth: 1

# scripts that run after cloning repository
install:
    - export GOVERSION=1.13.5
    - wget "https://storage.googleapis.com/golang/go$GOVERSION.linux-amd64.tar.gz"
    - tar xzf "go$GOVERSION.linux-amd64.tar.gz"
    - export GOROOT=$(pwd)/go
    - export PATH=$(pwd)/go/bin:$PATH
    - export GO111MODULE=on
    - export GOPROXY=direct
    - git clone --depth=1 https://github.com/coredns/coredns.git
    - git clone --depth=1 https://github.com/coredns/fallback.git

# scripts that run before build
before_build:
    - go env
    - go version

# custom build scripts
build_script:
    - cd fallback
    - git apply "$APPVEYOR_BUILD_FOLDER/fallback.patch"
    - go mod init github.com/coredns/fallback
    - cd ..
    - cd coredns
    - git apply "$APPVEYOR_BUILD_FOLDER/forward-quick-lookup-except.patch"
    - sed -i 's|forward:forward|fallback:github.com/coredns/fallback\nforward:forward\nproxy:github.com/coredns/proxy|g' plugin.cfg
    - sed -i 's|hosts:hosts|ads:github.com/c-mueller/ads\nhosts:hosts|g' plugin.cfg
    - sed -i 's|cache:cache|cache:cache\nredisc:github.com/miekg/redis|g' plugin.cfg
    - sed -i 's|rewrite:rewrite|rewrite:rewrite\nbogus:github.com/missdeer/bogus\nipset:github.com/missdeer/ipset|g' plugin.cfg
    - sed -i 's|replace (|replace (\n\tgithub.com/coredns/fallback => ../fallback|g' go.mod
    - env GOOS=linux GOARCH=amd64 make -j 2
    - echo "==============================================="
    - ./coredns -plugins
    - echo "==============================================="
    - make -j 2
    - cd ..

# scripts that run after build
after_build:
    - mkdir -p "distrib/coredns-$PREFIX" 
    - cp "$APPVEYOR_BUILD_FOLDER/coredns/coredns" "distrib/coredns-$PREFIX/coredns$SUFFIX"
    - cp "$APPVEYOR_BUILD_FOLDER/coredns/coredns" "distrib/coredns$SUFFIX"
    - cd distrib
    - curl -s -L git.io/corefile | bash
    - 7z a "coredns-$PREFIX.7z" "coredns-$PREFIX" Corefile
    - 7z a coredns.7z "coredns$SUFFIX"
    - md5sum "coredns$SUFFIX"
    - sha1sum "coredns$SUFFIX"
    - sha224sum "coredns$SUFFIX"
    - sha256sum "coredns$SUFFIX"
    - sha384sum "coredns$SUFFIX"
    - sha512sum "coredns$SUFFIX"
    - md5sum coredns.7z
    - sha1sum coredns.7z
    - sha224sum coredns.7z
    - sha256sum coredns.7z
    - sha384sum coredns.7z
    - sha512sum coredns.7z

artifacts:
    - path: distrib/coredns-$PREFIX.7z
      name: full_package
    - path: distrib/coredns.7z
      name: exe_only
